### ISSUE TITLE
Matching geography codes to their names

### ISSUE THREAD

**Issue by jvillacampa** [Health-SocialCare-Scotland/phsmethods#13]
One idea discussed in our team (QI) was to have a function to get the name of the health board based on the geography code. I have got a function that matches the geography code of many different types of areas (from constituencies and datazones to councils and boards) with their respective name. Would that be one worth adding to the package?

**Comment by jackhannah95** [comment]
Hi @jvillacampa. Sorry for the delay in replying. I haven't spoken to David or Lucinda but I'm assuming they know about it from the QI meeting, and I think it's a good idea. Do you think it'd be worth having a function to do the reverse as well? Or is that overkill?

**Comment by jvillacampa** [comment]
Cheers @jackhannah95. A reverse function would be good, but might need to think about it. It could be a bit tricky as sometimes areas of different geography levels share a name (e.g. Highland council and board). I'll prepare a pull request.
