### ISSUE TITLE
PQ Standard Reply Template

### ISSUE THREAD

**Issue by lucindalawrie** [Health-SocialCare-Scotland/phsmethods#28]
R Markdown template for producing PQ replies - will need a letter head template and some standard formatting e.g. a bold first paragraph for the PQ details, an optional table template. Majority however will be free text fields.

Under development as part of the QI R project.

**Comment by jackhannah95** [comment]
This seems like something that might be better suited to [phiproject](https://github.com/Health-SocialCare-Scotland/phiproject) than phsmethods. @alan-y and I have had aspirations of turning it into a `phstemplates` package containing all the various RMarkdown templates, plus standard templates for projects, scripts, shiny apps, leaflet maps, etc. I probably won't get much time to work on it before I go unfortunately, but Alan will hopefully be continuing on with it. Any thoughts Alan?

**Comment by alan-y** [comment]
Yeah I think `phstemplates` would be the best place for this template. It's reasonably straightforward to add it in as one of the RMarkdown templates in the package. Happy to help with it if needed

**Comment by lucindalawrie** [comment]
I agree, `phstemplates` seems like the best place for this to go. I'll create a branch of the `phiproject` repo and work on the PQ template in there then. Thanks both 😃
