### ISSUE TITLE
update to chi_check

### ISSUE THREAD

**Issue by graemegowans** [Health-SocialCare-Scotland/phsmethods#38]
Hey guys,

@alan-y suggested an update to the `chi_check` function to return a more informative result on missing values (NAs). Would you be happy for me to make a branch for this?

Thanks,

Graeme

**Comment by lucindalawrie** [comment]
Hi Graeme,

This sounds like a good idea. Happy for a branch to be created 👍 

Thanks,
Lucinda

**Comment by Moohan** [comment]
Hey, any update on this? Looks like the pull request is has been reviewed and is ready to merge to me. Only outstanding change was first merge to the latest, which @graemegowans did on 22 June.

Just asking as my pull request #41 is queued up behind this one 😛
